import type { Metadata } from "next";
import { Pricing } from "@/components/home/Pricing";
import { Navbar } from "@/components/home/Navbar";
import { Footer } from "@/components/home/Footer";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Pricing - Lexport AI | AI Contract Generation & E-Signatures",
  description:
    "Simple, transparent pricing for AI-powered contract generation, e-signatures, and payment collection. Start free, upgrade when you need more.",
  openGraph: {
    title: "Pricing - Lexport AI",
    description:
      "AI-powered contracts from $0/month. Generate, sign, and get paid — all in one platform.",
  },
};

export default function PricingPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      <Pricing />

      {/* FAQ */}
      <section className="py-16 sm:py-20 px-4 sm:px-6 lg:px-8 bg-white">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 text-center mb-10">
            Frequently asked questions
          </h2>
          <div className="divide-y divide-slate-200">
            {[
              {
                q: "Can I try Lexport for free?",
                a: "Yes! The Free plan includes 1 AI contract, 2 signature requests, and 3 AI chat messages per month — no credit card required.",
              },
              {
                q: "What happens when I hit my free limit?",
                a: "You'll see a prompt to upgrade. Your existing contracts and signatures remain accessible — you just can't create new ones until the next billing cycle or after upgrading.",
              },
              {
                q: "Can I cancel anytime?",
                a: "Absolutely. There are no long-term commitments. Cancel from your billing settings and you'll keep access until the end of your current period.",
              },
              {
                q: "Are the contracts legally binding?",
                a: "Yes. Contracts generated by Lexport are jurisdiction-aware and include legally binding e-signatures compliant with ESIGN, UETA, and eIDAS regulations.",
              },
              {
                q: "Which jurisdictions do you support?",
                a: "We support 120+ jurisdictions globally, with deep coverage for US states (California, Texas, New York), the UK, EU, and more.",
              },
              {
                q: "What's included in premium templates?",
                a: "Free users get access to 7 template types (NDAs, contractor agreements, consulting agreements, and more). Premium templates like SAFE Notes, Co-Founder Agreements, and MSAs are available for $9.99 each, or included free with Pro and Business plans.",
              },
            ].map((item) => (
              <details
                key={item.q}
                className="group py-4 sm:py-5 cursor-pointer"
              >
                <summary className="flex justify-between items-center text-sm sm:text-base font-medium text-slate-900 list-none">
                  {item.q}
                  <span className="ml-4 text-slate-400 group-open:rotate-45 transition-transform text-lg">
                    +
                  </span>
                </summary>
                <p className="mt-3 text-sm text-slate-600 leading-relaxed">
                  {item.a}
                </p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 sm:py-20 px-4 sm:px-6 lg:px-8 bg-slate-50">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 mb-4">
            Ready to get started?
          </h2>
          <p className="text-slate-600 mb-8">
            Create your first AI-powered contract in under a minute. No credit
            card required.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center justify-center bg-[#202e46] text-white px-8 py-3 rounded-xl font-semibold hover:bg-[#1a2539] transition-all hover:shadow-lg text-base"
          >
            Start for free
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}
